### ISSUE TITLE
Houston, we have a problem

### ISSUE THREAD

**Issue by alexchetv** [matreshkajs/matreshka.io#3]
userAgent:  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Error: Cannot read property 'length' of null

**Comment by finom** [comment]
Hmm, cannot reproduce. Are you still getting the same issue?

**Comment by finom** [comment]
Cannot reproduce, closing.
