### ISSUE TITLE
ENHANCEMENT: Add social media icons(github,twitter,gitter,etc.) at the top right corner of the page.

### ISSUE THREAD

**Issue by jaiag10** [matreshkajs/matreshka.io#6]

**Comment by finom** [comment]
Confused... Why do you need it?

**Comment by jaiag10** [comment]
Easier for sharing(user's perspective) if it is fixed at a corner from any part of the page.

**Comment by finom** [comment]
Can you draw an example (desktop/tablet/mobile)? Or at least show a website where this approach is used.

**Comment by jaiag10** [comment]
cyro.se - they have only one icon
udacity - they have icons at the bottom of the page.
gogoanime.io - they have at the top but icons used are not attractive.

**Comment by finom** [comment]
I don't have a budget to pay for a designer. Closing for now.
